# Generated by Django 4.1.1 on 2022-10-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20201101_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(max_length=15),
        ),
    ]
