# Generated by Django 4.1.1 on 2022-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_course_name_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(),
        ),
    ]
